### ISSUE TITLE
Error: Uncaught [Error: Your focus-trap needs to have at least one focusable element]

### ISSUE THREAD

**Issue by DAlekss** [focus-trap/focus-trap-react#91] opened 2020-08-05 13:33 UTC
The new 7.0.0/7.0.1 upgrade breaks down jest/enzyme tests with the error: 
Error: Uncaught [Error: Your focus-trap needs to have at least one focusable element].

The above error occurred in the <FocusTrap> component:
        in FocusTrap (created by WrapperComponent)
        in WrapperComponent

Seems that focus trap cannot locate any child element.
I have added the isolated test file as well as package.json  - everything is up to date there. 

[package.txt](https://github.com/focus-trap/focus-trap-react/files/5028670/package.txt)
[focustest.txt](https://github.com/focus-trap/focus-trap-react/files/5028726/focustest.txt)

**Comment by SeanMcP** [comment] 2020-08-13 15:18
[Here is a code sandbox that reproduces the error](https://codesandbox.io/s/focus-trap-react-enzyme-sutd9?file=/src/index.test.js), but I'm seeing the same error in versions `6.0.0` and `5.0.1`.

**Comment by stefcameron** [comment] 2020-08-13 16:33
@DAlekss I've experienced this myself with the project where I'm using `focus-trap-react`. What I found is that the challenge lies with [this delay](https://github.com/focus-trap/focus-trap/blob/master/index.js#L145) in `focus-trap` when the trap is activated.

With the `@testing-library/react`, this translates to making the test async and using `waitFor()`:
```javascript
test('check focus', async () => {
  render(<Component />);
  await waitFor(() => expect(screen.getByTestId('initial-focus-node')).toHaveFocus());
});
```
(assuming you have an `data-testid="initial-focus-node"` attribute set on the node that the focus trap should set initial focus to when it's activated, and that rendering `<Component/>` activates the trap)

I'm not sure why this update surfaces this problem; perhaps because 7.0.0 includes `focus-trap` 5.1.0, and maybe that delay is new in that version, which predates my time as a maintainer. Prior to 7.0.0, I believe the dependency was on `focus-trap@4.0.x`.

**Comment by stefcameron** [comment] 2020-08-15 23:14
Labeling this "not a bug" for now since I think it's more of a matter of dealing with async behavior in tests than an actual bug in the code.

**Comment by bdelaforest** [comment] 2020-09-03 11:59
I had the same issue in my tests. Using the [`fallbackFocus`](https://github.com/focus-trap/focus-trap#usage) option helped me get rid of the error without rewriting any test!

**Comment by stefcameron** [comment] 2020-09-21 17:59
I'm going to close this since I don't think this is actually a bug in focus-trap-react.

However, FYI, https://github.com/focus-trap/focus-trap/pull/154 just added a new trap option, `delayInitialFocus`, which you can now set to `false` in order to have the initial focus node to be immediately focused when the trap is activated, rather than waiting for the next event loop pass. This will published very soon in `focus-trap@6.1.0` (as soon as NPM is back online; service is down right now).

**Closed by stefcameron** 2020-09-21 17:59 UTC
Labels: not a bug

**Comment by OmkarRajam** [comment] 2022-04-11 21:47
> [Here is a code sandbox that reproduces the error](https://codesandbox.io/s/focus-trap-react-enzyme-sutd9?file=/src/index.test.js), but I'm seeing the same error in versions `6.0.0` and `5.0.1`.

@SeanMcP I noticed that one way to fix this issue is to wrap your tabbable elements with a `<div>`. Then the tests passed. See this [forked code sandbox](https://codesandbox.io/s/focus-trap-react-enzyme-forked-4mdfzp?file=/src/index.test.js:400-418). The only addition I did was to add a `<div>` around `{child}` like this -> `<div>{child}</div>`. Now the test is passing.

**Comment by ullas1000** [comment] 2023-04-06 05:39
this is due to none availability of tabbable controls.
https://devphobia.com/posts/Your-focus-trap-must-have-at-least-one-container

**Comment by stefcameron** [comment] 2023-04-07 14:48
Please see this help entry in focus-trap's README which explains why this error happens, and what options you can use on the `focusTrapOptions` prop to try to fix the issue): https://github.com/focus-trap/focus-trap/blob/master/README.md#error-your-focus-trap-must-have-at-least-one-container-with-at-least-one-tabbable-node-in-it-at-all-times
