### ISSUE TITLE
Main app compiled with 'module not found' in dependency

### ISSUE THREAD

**Issue by chubun** [focus-trap/focus-trap-react#374] opened 2021-05-26 16:27 UTC
I have an npm package (say, my-test-lib) and use it in a react app (say, my-test-app). my-test-lib can be compiled and published without problems.  However, I get the message below when compiling my-test-app:
```
ERROR in c:/Projects/my-test-lib/lib/components/Elements/ModalForm.js
Module not found: Error: Can't resolve 'focus-trap-react' in 'c:\Projects\my-test-lib\lib\components\Elements'
```
I do a 'dir' on the lib (linked locally with 'npm link' for testing) and it seems to be there:
```
dir c:\Projects\my-test-app\node_modules\my-test-lib\node_modules\focus-trap-react

 Volume in drive C has no label.
 Volume Serial Number is 1452-227B

 Directory of c:\Projects\portal-web\node_modules\my-test-lib\node_modules\focus-trap-react

05/25/2021  06:30 PM    <DIR>          .
05/25/2021  06:30 PM    <DIR>          ..
10/26/1985  03:15 AM             7,579 CHANGELOG.md
05/25/2021  06:30 PM    <DIR>          dist
10/26/1985  03:15 AM               443 index.d.ts
10/26/1985  03:15 AM             1,079 LICENSE
10/26/1985  03:15 AM             3,422 package.json
10/26/1985  03:15 AM            13,794 README.md
10/26/1985  03:15 AM             3,633 SECURITY.md
05/25/2021  06:30 PM    <DIR>          src
               6 File(s)         29,950 bytes
               4 Dir(s)  1,854,537,859,072 bytes free
```
The lib uses other packages, but the compiler singles out only forcus-trap-react.  
If I also install focus-trap-react on my-test-app, the error goes away, but so does the component.  It won't display and there are no error messages.  
Not sure what I miss.  Is there a rule that the component has to be top level or anything like that?

**Comment by stefcameron** [comment] 2021-05-26 18:06
@chubun Hey, that's a bit of a head scratcher... 🤔 Since the error goes away when you install `focus-trap-react` in the parent project (`my-test-app`), maybe this is a problem with your build system not following symlinks (since you say you're linking `my-test-lib` to `my-test-app` with `npm link`)? Just a guess.

> Is there a rule that the component has to be top level or anything like that?

There's nothing that says `focus-trap-react` must be a the top of the module resolution tree, if that's what you're asking here.

Another way to test this is, assuming `my-test-lib` is a directory that contains a `package.json` describing that lib, build your lib package and then in `my-test-app`, change your package.json to reference `my-test-lib` by path, like `"my-test-lib": "../my-test-lib"` (assuming `my-test-app` and `my-test-lib` are sibling directories), and then `npm install` that and see if the problem is resolved. Unlike `npm link`, this way shouldn't involve any symlinks. See if that clears the error up. If so, I would then say it points to some issue with your build, not `focus-trap-react`.

**Comment by stefcameron** [comment] 2022-04-22 14:24
Closing. If it's still an issue, feel free to re-open.

**Closed by stefcameron** 2022-04-22 14:24 UTC
Labels: question
